# Generated by Django 4.2 on 2023-06-01 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(verbose_name='Course Number')),
                ('title', models.CharField(max_length=31, verbose_name='Course')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='profile_pics')),
                ('tutorPermissions', models.BooleanField(default=False, verbose_name='Права тьютора')),
                ('initiative', models.BooleanField(default=False, verbose_name='Инициатива')),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='Profiles', to='users.course', verbose_name='Course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
