# Generated by Django 4.2 on 2023-06-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutors', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DockerPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postText', models.TextField(default='Тут пока нет никаких ссылок', verbose_name='Текст поста в хранилище')),
                ('course', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='DockerPosts', to='users.course', verbose_name='Course')),
                ('discipline', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='DockerPosts', to='tutors.subject')),
            ],
            options={
                'verbose_name': 'Пост в Хранилище',
                'verbose_name_plural': 'Посты в Хранилище',
            },
        ),
    ]
