# Generated by Django 4.2 on 2023-06-03 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dockerpost',
            name='title',
            field=models.CharField(default='Заголовок', max_length=511, verbose_name='Заголовок'),
        ),
    ]
