# Generated by Django 4.2 on 2023-06-01 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Общие', max_length=127, verbose_name='Предмет')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.course')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='TutorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63, verbose_name='Имя')),
                ('contacts', models.TextField(verbose_name='Контакты')),
                ('discipline', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tutors', to='tutors.subject')),
                ('profile', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tutors', to='users.profile')),
            ],
            options={
                'verbose_name': 'Информация о Тьюторе',
                'verbose_name_plural': 'Информация о Тьюторах',
            },
        ),
    ]
